spring:
  config:
    activate:
      on-profile: "real"
    import: application-secret.yml

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: ${datasource.driver}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/${database}/schema.sql

  redis:
    host: ${redis.host}
    port: ${redis.port}

logging:
  level:
    org.springframework.web: debug