database: h2

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/letmeclean
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.web: debug