spring:
  config:
    activate:
      on-profile: "local"
    import:
      - application-secret.yml
      - application-kakao.yml

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password:
    driver-class-name: ${datasource.driver}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ${redis.host}
    port: ${redis.port}
logging:
  level:
    org.springframework.web: debug